### ISSUE TITLE
Cannot create JapxCodable with nil id

### ISSUE THREAD

**Issue by heyjared** [infinum/Japx#9]
From the JSONAPI specification website: 

> Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.

However, it is not possible to create a `JapxCodable` without an `id`.

**Comment by gfvilela** [comment]
Where did you use JapxEncodable? Because I have the same problem

**Comment by Truba** [comment]
Hi @gfvilela,
The original issue was with creating objects on the client (don't have the id yet) and then calling CREATE on the server.
Similar to how Codable is actually Encodable & Decodable, JapxCodable is actually JapxDecodable & JapxEncodable.
JapxDecodable requires id to be non optional, since it should be used for decoding data from server.
JapxEncodable doesn't have that requirement since it should be used for encoding data and sending to the server.
